= Deployment to Tomcat

== Intro

* Installing tomcat
* Configuring tomcat
* Configuring apache
* Jenkins job for deploy


== Installing tomcat

 sudo apt-get install tomcat7

Will

* Add tomcat user
* Setup init.d script to start/stop etc
* Add tomcat server at `/var/lib/tomcat7/`
** Logs in `/var/log/tomcat7/`
** Configuration in `/etc/tomcat7/`
* Start tomcat server

You can verify this by a browser on `ip.address.of.server:8080` where you should see a tomcat *It works !* page


== Configuring tomcat

There is is a known issue with Ubuntu and Tomcat, startup is slow, due to the use of `/dev/random` as its RNG, due to a lack of entropy (upwards of 5 minutes).
You can correct this by modifying `/etc/default/tomcat7`.
On the the JAVA_OPTS line, add the following:

 -Djava.security.egd=file:/dev/./urandom

*CATALINA_HOME* is `/usr/share/tomcat7/` and in the bin folder, we should place a file:

[source,groovy,indent=0]
.setenv.sh
----
CATALINA_OPTS="-server -noverify -Xshare:off -Xms512M -Xmx512M -XX:MaxPermSize=256M -XX:PermSize=128M"
----


== Configuring apache



== Jenkins job for deploy





== Literature

* http://grails.github.io/grails-howtos/en/performanceTuning.html[]


////

[source,html,indent=0]
.views/gone.gsp
----

----


[source,groovy,indent=0]
.views/gone.gsp
----

----


////
