= HTML5 and CSS3 (and Less)

== Intro


Topics for now

* Will focus on new elements in HTML5
* CSS
** Ways to do css
** Bet practices
* Less (and why this is better than css)


== HTML5

* More-Descriptive Markup
* Less verbose in some areas
* Better Forms
* Advanced Selectors
* Visual Effects
* Better support for creating applications
* Web Sockets
* Client-Side Storage

<<<

[source,html,indent=0]
.Before
----
<script language="javascript" type="text/javascript">
----

[source,html,indent=0]
.after
----
<script>
----


== Deprecated markup

* basefont
* big
* center
* font
* s
* strike
* tt
* u
* frame
* frameset
* noframes

Some replaced by better options

* acronym -> abbr .
* applet -> object .
* dir -> ul .


== Invalid attributes


* align
* link , vlink , alink , and text attributes on the body tag
* bgcolor
* height and width
* scrolling on the iframe element
* valign
* hspace and vspace
* cellpadding , cellspacing , and border on table


== Common bad practice

Using too many `div` elements

[source,html,indent=0]
----
<div id="content">
	<div id="navigation_wrapper">
		<div id="navigationbar">
			Some navigation bar markup
		</div>
	</div>
</div>
----


== Use instead

* `<header>` A header region of a page or section.
* `<footer>` A footer region of a page or section.
* `<nav>` A navigation region of a page or section.
* `<section>` A logical region of a page or a grouping of content.
* `<article>` An article or complete piece of content.
* `<aside>` Secondary or related content.


== Basic structure and doctype

[source,html,indent=0]
.index.html
----
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<title>Battlestar Galactica Database</title>
	</head>
	<body>
	</body>
</html>
----

Gone is the old doctype

 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


== Headers and footers

*Headers*

* Headers may contain different content, not just a `h1` tag.
* Each section may have its own header.

*Footer*

* Common for navigation structure
* Multiple footers allowed in specification

TIP: Add a unique id, so you can locate the element

[source,html,indent=0]
----
<header id="page_header">
	<h1>Battlestar Galactica - Ships</h1>
</header>
----

== Navigation

Explicitly marking up navigation with the `nav` element is best practice, to help screen-readers etc.

[source,html,indent=0]
----
<nav id="main_page_navigation">
	<ul>
		<li><a href="#">Ships</a></li>
		<li><a href="#">Persons</a></li>
	</ul>
</nav>
----


== Sections and Articles

* Sections are the logical regions of a page, typically replacing a div.
* Group together elements, but use `<article>` for the actual content, elements in a list of ships with information, blog posts etc.

*LaTeX equivalent*

* `<section>` -> section
* `<article>` -> sub-section



== Asides

*`<aside>`* nested in article

Use for fx

* pull quotes
* diagrams
* additional thoughts
' related links

Do not use for

* global sidebar -> use section







== Styling - CSS

Inline style (Bad style)

[source,html,indent=0]
----
<h1 style="color: #1A4491">BSG</h1>
----

In header

[source,html,indent=0]
----
<style>
    h1 {
        color: #255b17;
    }
</style>
----

In separate file

[source,css,indent=0]
.style.css
----
h1 {
    color: #255b17;
}
----


== Selectors

[source,css,indent=0]
.style.css
----
<h1 class="bsg_header" id="page_header">BSG</h1>
----

[source,css,indent=0]
.style.css
----
h1 {
    color: #255b17;
}
.bsg_header {
    padding: 10px;
}
#page_header {
    margin: 5px;
    border: dashed #006dba 2px;
}
----

Selecting markup element, class or id.

== Selectors (2)

A nice introduction to css selectors: https://css-tricks.com/how-css-selectors-work[]


== Styling a table

Styling a table - might be example below
-Stribing a row (separating content from presentation
-Aligning data

== Styling forms

Forms udvidet:

autofocus

placeholder

autocomplete="off" for password fields


title attribute

== Less intro

   Asset pipeline - less plugin

TODO Make an example, where css duplicates a value -> variables needed.



////






Print-styles

Mobile interfaces

Multicolumn


Rounding edges s.153

shadows 157

rotation 161

fonts 164






Også:

Test coverage

Codenarc


Bootstrap intro.






input[required]:invalid, input[pattern]:invalid{
border-color: #A5340B;
}
input[required]:valid, input[pattern]:valid{
border-color: #0B9900;
}



[source,html,indent=0]
.views/gone.gsp
----
<!DOCTYPE html>
<html>
  <head>
    <title>Lost...</title>
	</head>
	<body>
      <h1>
		He's Gone, Jim - he's dead!
	  </h1>
	  <h2>We really could not find what you were looking for</h2>
	</body>
</html>
----

In interactive mode

 url-mappings-report



== Best practices

* Controllers must be thin
** Logic placed in services
* Use the smartest databinding method - depending on your problem
** Command objects can encapsulate business logic



== Exercise

IMPORTANT: Implement and test the statistic task, and your preferred way to search for ships

== Literature

* http://www.w3.org/TR/html5/[]
* http://www.w3.org/Style/CSS/current-work[]
* http://caniuse.com/[]

* https://css-tricks.com/how-css-selectors-work[]


////
