= Ajax and Rest

[#ajax]
== Ajax

*Asynchronous JavaScript and XML*

* XMLHttpRequest (XHR) object
* No need to reload entire page
* Requests triggered by javascript
* Browser specific implementation

[#get-vs-post]
== Get vs Post

*GET*

* Non-destructive operations
* May be cached by the browser
** Can lead to unpredicted behavior
* Generally send all of their data in a query string

*POST*

* Destructive operations
* Generally not cached by the browser
* Query string can be part of the URL, but the data tends to be sent separately as post data.


[#callback]
== Callback functions

*A is for asynchronous*

[source,html,indent=0]
----
<button id="get-activation">GET Activation</button>
<button id="post-activation">POST Activation</button>
<div id="ajax-content">&nbsp;</div>
----

[source,javascript,indent=0]
----
$('#get-activation').on( 'click' , function() {
	$.get( '${g.createLink(controller: 'peopleAjaxDemo', action: 'quote')}', function(response) {
		$('#ajax-content').html(response);
	});
});
----

[source,javascript,indent=0]
----
$('#post-activation').on( 'click' , function() {
	$.post( '${g.createLink(controller: 'peopleAjaxDemo', action: 'quote')}', function(response) {
		$('#ajax-content').html(response);
	});
});
----


== Loading into a DOM element


[source,javascript,indent=0]
----
$('#load-activation').on( 'click' , function() {
	$('#ajax-content').load( '${g.createLink(controller: 'peopleAjaxDemo', action: 'quote')}' );
});
----


== Handling errors and Full configuration

[source,javascript,indent=0]
----
$('#ajax-activation').on( 'click' , function() {
$.ajax({
	url: '${g.createLink(controller: 'peopleAjaxDemo', action: 'quoteJson')}',
	data: { id: 42 }, // Not used here
	type: "GET",
	dataType : "json", // Expected return type: text, html, script, json, jsonp, xml
	success: function( json ) {
		$('#ajax-content').html(json.quote);
		alert(json.status);
	},
	error: function( xhr, status, errorThrown ) {
		alert( "Auch. something did not go as planned :(" );
		console.log( "Error: " + errorThrown );
		console.log( "Status: " + status );
		console.log( xhr );
	},
	complete: function( xhr, status ) {
		console.log("The request is done")
	}
});
});
----


== Loading indicator

*Bind to global events*

[source,html,indent=0]
----
<span id="loading-indicator">Loading...</span>
----

[source,css,indent=0]
----
#loading-indicator {
	display: none;
	background-color: dodgerblue;
	padding-left: 20px;
	padding-right: 20px;
}
----

[source,javascript,indent=0]
----
$(document).bind("ajaxSend", function(){
	$("#loading-indicator").fadeIn();
}).bind("ajaxComplete", function(){
	$("#loading-indicator").fadeOut();
});
----


== Controller output

[source,groovy,indent=0]
----
def index() {
	[people: Person.list()]
}
----

[source,groovy,indent=0]
----
def quote() {
	String quote = quoteService.randomQuote
	render( quote )
}
----

[source,groovy,indent=0]
----

def quoteJson() {
	Map result = [
		quote: 	quoteService.randomQuote,
		status: 'You received a quote'
	]
	render( result as JSON )
}
----

== Mixing output

*HTML inside json*

[source,groovy,indent=0]
----
	def somePersonJson() {
		Person person = Person.list([sort:'lastUpdated', order:'desc',max:1]).first()
		String personHtml = g.render(template: 'person', model: [person: person])
		Map jsonMap = [
				id: person.id,
				quote: 	"<h2>${quoteService.randomQuote}</h2>",
		        lastUpdated: person.lastUpdated,
				personHtml: personHtml
		]
		render( jsonMap as JSON )
	}

----

<<<


[source,javascript,indent=0]
----
$('#duplication-activation').on( 'click' , function() {
	$.ajax({
		url: '${g.createLink(controller: 'peopleAjaxDemo', action: 'somePersonJson')}',
		type: "GET",
		dataType : "json", // Expected return type: text, html, script, json, jsonp, xml
		success: function( json ) {
			console.debug("Retrieved person with id: " + json.id)
			console.debug("Last updated is: " + json.lastUpdated)
			var duplicatePerson = $(json.personHtml)
			$('#ajax-content').html(json.quote);
			$('#people').append( duplicatePerson );
		},
		error: function( xhr, status, errorThrown ) {
			alert( "Auch. Thats not good :(" );
		}
	});
});
----


[#rest]
== Rest

"Representational State Transfer (REST) is a software architecture style consisting of guidelines and best practices for creating scalable web services. +
 +
REST is a coordinated set of constraints applied to the design of components in a distributed hypermedia system that can lead to a more performant and maintainable architecture."
-- Wikipedia (http://en.wikipedia.org/wiki/Representational_state_transfer[])


[#constraints]
== Formal REST constraints

* Client–server
* Stateless
* Cacheable
* Layered system
* Code on demand (optional)
* Uniform interface
** Identification of resources
** Manipulation of resources through these representations
** Self-descriptive messages
** Hypermedia as the engine of application state (HATEOAS)

TIP: If all constraints are applied: Restfull webservice



[#http-methods]
== HTTP Methods



TIP: In Grails you can define which methods are allowed to activate with the different HTTP methods using `static allowedMethods ...`


== Rest in Grails

Lets make a simple message Domain Class, and annotate it with `@Resource`

[source,groovy,indent=0]
----
package dk.dm844.bsg

import grails.rest.Resource

@Resource
class Message {

	Person from
	String message

	Date dateCreated

	static constraints = {
			message blank: false
	}
}
----

<<<

This is a complete Restfull class - without a controller.


[#url-mappings]
== Url Mappings

Lets assume we also wish to expose persons as a `info` endpoint

Add this to `UrlMappings.groovy`

[source,groovy,indent=0]
----
class UrlMappings {

	static mappings = {
		"/info"(resources: 'message') // <1>

        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
	}
}
----

<1>  added mapping line

[#url-mappings-report]
== Url Mappings report


 grails url-mappings-report

----
...
Controller: message
 |   GET    | /info                | Action: index
 |   GET    | /info/create         | Action: create
 |   POST   | /info                | Action: save
 |   GET    | /info/${id}          | Action: show
 |   GET    | /info/${id}/edit     | Action: edit
 |   PUT    | /info/${id}          | Action: update
 |  PATCH   | /info/${id}          | Action: patch
 |  DELETE  | /info/${id}          | Action: delete

----


[#check-it-out]
== Lets test it

*Store a message*

 curl -i -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d '{"from":{"id":1},"message": "Stored using curl"}' http://localhost:8088/bsg/info

*Retrieve list of messages*

 curl -i -X GET -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8088/bsg/info

*Retrieve message with id 1*

 curl -i -X GET -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8088/bsg/info/1

*Update partially message 1*

 curl -i -X PATCH -H "Content-Type: application/json" -H "Accept: application/json" -d '{"from":{"id":2},"message": "Stored using curl"}' http://localhost:8088/bsg/info/1

*Delete message again*

 curl -i -X DELETE -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8088/bsg/info/1


[#output-with-format]
== Determining output in Controller

[source,groovy,indent=0]
----
def personOutputDemo() {
	Person person = Person.list([sort:'lastUpdated', order:'desc',max:1]).first()

	withFormat {
		html { render(template: 'person', model: [person: person])}
		xml { render person as XML }
		json { render person as JSON }
	}
	// Or respond person - if all identical
}
----

[#renderer]
== Defining output - Renderer

`grails-app/conf/spring/resources.groovy`
[source,groovy,indent=0]
----
import dk.dm844.bsg.Message
import grails.rest.render.hal.HalJsonCollectionRenderer
import grails.rest.render.json.JsonRenderer

beans = {

	messageRenderer( JsonRenderer, Message) {
		excludes = ['from']
	}

	messageCollectionRenderer( HalJsonCollectionRenderer, Message) {
		includes = ['from']
	}
}
----



[#marshaller]
== Defining output - Marshaller

[source,groovy,indent=0]
----
def marshallerDemo() {
	JSON.registerObjectMarshaller(Person) {
		def map = [
		        name: it.name,
				updated: g.formatDate(date: it.lastUpdated, format: 'yyyy-MM-dd')
		]
		return map
	}
	render( Person.list() as JSON)
}
----



[#exercise]
== Exercise

You can clone this project from git using

 git clone https://github.com/JacobAae/dm844-sample-project.git

Try to do the following

* Make a new domain class for REST, a user with names, password-hash, salt etc etc
* Customize the output, so sensitive info is not included


[#literature]
== Literature

* https://learn.jquery.com/ajax/
* https://www.youtube.com/watch?v=8xYi9n0pYFs&index=40&list=PLgGXSWYM2FpPHX5e32pBdZn1CuJo1oGc0[RESTful Grails 2 (Conference video)]

////

* Chapter 13 in Grails in Action


[#one-page-apps]
== One-page apps

Angular example from Peters book


[#]
==








[source,html,indent=0]
----

----


[source,groovy,indent=0]
----

----


[source,javascript,indent=0]
----

----



////
